#define default_PWM_frequency 1.0/20000.0
#define left_motor_A_pin PB_13
#define left_motor_B_pin PB_14
#define right_motor_A_pin PB_15
#define right_motor_B_pin PA_11
#define left_encoder_A_pin PA_13
#define left_encoder_B_pin PA_14
#define right_encoder_A_pin PC_2
#define right_encoder_B_pin PC_3
#define mybutton_pin USER_BUTTON
